### ISSUE TITLE
Thanks so much omg!

### ISSUE THREAD

**Issue by ycmjason** [faressoft/inquirer-checkbox-plus-prompt#1]

**Comment by faressoft** [comment]
You are most welcome 👍 
Please subscribe (follow) my GitHub if you like my work

**Comment by ycmjason** [comment]
this is really nice to have as https://github.com/mokkabonna/inquirer-autocomplete-prompt refused to add `checkbox` support.

**Comment by faressoft** [comment]
Yes my plugin is influenced by the autocomplete plugin. I am going to publish new cool plugins soon.

**Comment by ycmjason** [comment]
Amazing! Thank you!
