### ISSUE TITLE
fix: add chalk as dependencies ? 

### ISSUE THREAD

**Issue by edisonLzy** [faressoft/inquirer-checkbox-plus-prompt#13]
hi!! Why chalk in code , not in dependencies ?

**Comment by G233** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/39009225/197769086-b5d805eb-d809-4232-88ea-50275389328b.png">
looks like same issues

**Comment by edisonLzy** [comment]
> <img alt="image" width="1342" src="https://user-images.githubusercontent.com/39009225/197769086-b5d805eb-d809-4232-88ea-50275389328b.png">
> 
> looks like same issues

if you use pnpm , you can use `packageExtensions` to resolve.

```
  "pnpm": {
    "packageExtensions": {
      "inquirer-checkbox-plus-prompt": {
        "dependencies": {
          "chalk": "^4.0.0"
        }
      },
    }
  }
```

**Comment by G233** [comment]
> > <img alt="image" width="1342" src="https://user-images.githubusercontent.com/39009225/197769086-b5d805eb-d809-4232-88ea-50275389328b.png">
> > looks like same issues
> 
> if you use pnpm , you can use `packageExtensions` to resolve.
> 
> ```
>   "pnpm": {
>     "packageExtensions": {
>       "inquirer-checkbox-plus-prompt": {
>         "dependencies": {
>           "chalk": "^4.0.0"
>         }
>       },
>     }
>   }
> ```

its working~  thanks~
